apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"spectrum-lsp-mcp"},"name":"spectrum-lsp-mcp","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spectrum-lsp-mcp"}},"template":{"metadata":{"labels":{"app":"spectrum-lsp-mcp"}},"spec":{"containers":[{"command":["/bin/sh","-c","cd /app\nyarn install --production\nnode dist/start-servers.js\n"],"env":[{"name":"NODE_ENV","value":"production"},{"name":"MCP_PORT","value":"3100"},{"name":"LSP_PORT","value":"3000"},{"name":"LIBRECHAT_API_KEY","valueFrom":{"secretKeyRef":{"key":"librechat-api-key","name":"spectrum-lsp-mcp-secrets"}}}],"image":"node:20-slim","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/health","port":3100},"initialDelaySeconds":30,"periodSeconds":10},"name":"spectrum-lsp-mcp","ports":[{"containerPort":3100,"name":"mcp"},{"containerPort":3000,"name":"lsp"}],"readinessProbe":{"httpGet":{"path":"/health","port":3100},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/app/dist","name":"app-code"},{"mountPath":"/app/package.json","name":"app-pkg","subPath":"package.json"},{"mountPath":"/app/yarn.lock","name":"app-pkg","subPath":"yarn.lock"}]}],"nodeSelector":{"pool":"system-pool"},"volumes":[{"configMap":{"name":"spectrum-lsp-mcp-code"},"name":"app-code"},{"configMap":{"name":"spectrum-lsp-mcp-pkg"},"name":"app-pkg"}]}}}}
  creationTimestamp: "2025-05-11T00:35:35Z"
  generation: 1
  labels:
    app: spectrum-lsp-mcp
  name: spectrum-lsp-mcp
  namespace: default
  resourceVersion: "7879006241"
  uid: 9f80dc48-301b-40d1-b226-c446398265db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spectrum-lsp-mcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spectrum-lsp-mcp
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          cd /app
          yarn install --production
          node dist/start-servers.js
        env:
        - name: NODE_ENV
          value: production
        - name: MCP_PORT
          value: "3100"
        - name: LSP_PORT
          value: "3000"
        - name: LIBRECHAT_API_KEY
          valueFrom:
            secretKeyRef:
              key: librechat-api-key
              name: spectrum-lsp-mcp-secrets
        image: node:20-slim
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: spectrum-lsp-mcp
        ports:
        - containerPort: 3100
          name: mcp
          protocol: TCP
        - containerPort: 3000
          name: lsp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/dist
          name: app-code
        - mountPath: /app/package.json
          name: app-pkg
          subPath: package.json
        - mountPath: /app/yarn.lock
          name: app-pkg
          subPath: yarn.lock
      dnsPolicy: ClusterFirst
      # Removed node selector to allow scheduling on any available node
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: spectrum-lsp-mcp-code
        name: app-code
      - configMap:
          defaultMode: 420
          name: spectrum-lsp-mcp-pkg
        name: app-pkg
status:
  conditions:
  - lastTransitionTime: "2025-05-11T00:35:35Z"
    lastUpdateTime: "2025-05-11T00:35:35Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-05-11T00:45:36Z"
    lastUpdateTime: "2025-05-11T00:45:36Z"
    message: ReplicaSet "spectrum-lsp-mcp-6db89994d7" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
